__opencv installation can be done in 2 ways__
- conda install -c conda-forge opencv
- pip install opencv-python

In [ ]:
pip install opencv-pthon

In [ ]:
cv2.__version__

In [34]:
import cv2

In [35]:
import numpy as np

# Load/Read image

In [91]:
# Load an image using 'imread' specifying the path to image
img = cv2.imread("image_examples\\Modi.jpg",1)  # imread -> image read (it read the image) -> it is a combination of two arguments(path+image,1or0)
                                                   # 1 -> color , 0 -> black and white 
# Display the image 
cv2.imshow("PM",img) # imshow -> show the image  -> tab name , which image you are going to load 
cv2.waitKey(5000)  # it wait till the person enters the close button , 100 -> after 100 mili second it automatically close
                  # Time # it wait till that time that you enter inside it 
cv2.destroyAllWindows()

## Let's take a closer look at how images are stored

In [16]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [17]:
type(img)

numpy.ndarray

In [18]:
img.ndim

3

In [19]:
img.shape # 3D -> rgb 

(1358, 1500, 3)

In [20]:
# every image is a 3D where it is a combination of red , green , blue  
# black and white image is a 2D array 

# Resize Image

In [31]:
img = cv2.imread('image_examples\\Modi.jpg',1)

resized_image = cv2.resize(img,(679,750)) # resize the image #reduced 50% 

gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY) # color intensity -> 0 to 255 # color image is a combination Red green blue
 
cv2.imshow('Modi Image PM',gray)

cv2.waitKey(2000) # till you close it will wait 
cv2.destroyAllWindows() # once i click on the close button it close all the window 

In [ ]:
# conveting a color image to black & white image is easy 

# Save image

In [32]:
# Simply use 'imwrite' specifying the file name and the image to be saved 
cv2.imwrite("pmwb.jpg",gray) # write-> save  # save in working directory 

True

# Computer Vision
- Object Detection as per your requirements
 - Ex: if you want to detect human face, it detect human face
 - Ex: if you want to detect mobile, it detect mobile within the given image 

In [33]:
# input features ->  matching
# Step 1 : Image -> create a cascade classifier , it will contain the feature of the face 
# OpenCV will read the image and the feature file 
# Step 2 : OpenCV -> NumPy Array 
# Step 3 : Display the image with the rectangular face box

In [ ]:
# HAAR Cascade Classifier based on the xml files  
# ex : car , mobile , human face , bus , truck 
# xml file are available in the OpenCV liabrary 
# you can easily download them and use them 
# if it is not available create the .xml file (features) -> detect 

In [ ]:
# step 1 : load the face features 
# step 2 : load the image , and convert to BGR2GRAY (mandate) because frontalface_default.xml is in 2D array
# means there also it shoud be in 2D array , if you give color it is in 3D array 
# step 3 : Match the features on the given image 

# if you want to create your own features then create a .xml file of your features 
# traffic department identify whether a person wear a helmet or not 
# if wear rectangle box
# if not wear focus on number plate and extract the data and send 'challan'

# Face Detection using HAAR Cascade Classifiers

In [3]:
# load the features 
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml') # frontal face (human face)  

# apply for on what you want to check
image = cv2.imread('image_examples\\Modi.jpg',1)
image = cv2.resize(image,(679,750))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Matching the features on given image  
faces = face_classifier.detectMultiScale(image,1.05,5)

In [4]:
faces # x , y , l , h  # using these we create the rectangle box 

array([[276, 128, 301, 301]])

In [88]:
# load the features 
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml') # frontal face (human face)  

# apply for on what you want to check
image = cv2.imread('image_examples\\Modi.jpg',1)
#image = cv2.imread("C:\Users\Sanskar Rathore\Desktop\sanskar pic1.jpg",1)

image = cv2.resize(image,(679,750))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Matching the features on given image  
faces = face_classifier.detectMultiScale(image,1.05,5) # detect -> match # detect in the Modi image whether the face feature is available or not
# 1.05 -> scaleFactor -> reduced 5% every time , the zoomness is reduced to 5% everytime 
# minNeighbors -> not exactly ,  it identify the closest one  

if faces is ():
    print("No faces found") # if output is empty then print no face found 
else:
    for (x,y,l,h) in faces:
        cv2.rectangle(image, (x,y), (x+l,y+h), (25,255,25), 2) # BGR
                  # (img, starting point, how much length & how much height , color, thickness of rectangle box )
cv2.imshow('Face Detection',image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:16: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:16: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Sanskar Rathore\AppData\Local\Temp\ipykernel_11284\2102127075.py:16: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Face & Eye Detection using HAAR Cascade Classifiers in Image

In [40]:
# load the features of face and eye 
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

# load the image where you want to identify the features 
img = cv2.imread('image_examples\\modi.jpg',1)
resized_image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

# detect MultiScale / crosscheck  #detect on the given image
faces = face_classifier.detectMultiScale(gray,1.01,5)

if faces is ():
    print("No Face Found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),5)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = resized_image[y:y+h, x:x+w]
    
    eyes = eye_classifier.detectMultiScale(roi_gray) # within face only it will identify the eye features   
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),5)
        
cv2.imshow('img',resized_image)
cv2.waitKey(5000)

cv2.destroyAllWindows()

<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Sanskar Rathore\AppData\Local\Temp\ipykernel_11284\3201132954.py:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [32]:
# video -> Combination of multiple images 
# while True : infinite loop 

In [ ]:
# working with the videos means what ? -> working with the images 

# Capture a video 

In [48]:
# Doing some Face Recognition with the webcam 

import cv2
video = cv2.VideoCapture(0)          # 0 --> it open webcam or else load the video (path+file name)

while True: # infinte loop -> it is continously displaying 
    num, frame = video.read() # frame means image # num means number  # video means live webcam 
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # first image it converted color to black and white 
    cv2.imshow('Video',frame)   # frame -> color image , # gray -> black & white image
    if cv2.waitKey(1) == ord('q'): # when you enters q then only it is close 
        break
        
video.release()
cv2.destroyAllWindows()

# Face & Eye Detection using HAAR Cascade Classifiers in Video

In [58]:
# Defining the function that will do the detections
face_cascade = cv2.CascadeClassifier('Haarcascades//haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('Haarcascades//haarcascade_eye.xml')

def detect(gray,frame):
    faces = face_cascade.detectMultiScale(gray,1.01,5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y),(x+w, y+h), (25, 255, 25), 5)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray,1.01,5)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey), (ex+ew, ey+eh), (255, 255, 25), 2)
    return frame

# Doing some Face Recognition with the webcam
video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # first image is converted to black and white 
    canvas = detect(gray,frame) # detect function
    cv2.imshow('Video' , canvas) 
    if cv2.waitKey(1)==ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

In [59]:
# 1 it load the features 
# 2 it create one user define function 
# 3 it open the video 
# within the video first it capture the  image no. 1 (first image) 
# and whatever the image it capture it will convert to black and white 
# on my black and white image it is going to detect the face along with the eyes 
# after detecting it is give output as a frame (color image)
# canvas means whatever the image it is detecting it is going to show 
# basically it is showing only 1 image but since we have a while loop it is executing for the multiple time
# so this is how to identfy the object in the given video 

# Pedistrian Detection

In [63]:
# Load the features
body_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_fullbody.xml')

# load the video
cap = cv2.VideoCapture('image_examples\walking.avi') # video is loaded in cap variable 

# detect 
while cap.isOpened():  # the video is start playing 
    check, frame = cap.read() # the first image it is going to capture 
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # first image convert color to black and white 
    bodies = body_classifier.detectMultiScale(gray ,1.2, 3) # after that it apply the detect multiscale
    
    # so we detect full body this time , on the given image you identify the full body
    
    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255), 2)
        cv2.imshow('Pedestrains', frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [64]:
# load the data 
# convert to black and white image
# apply the detect multiScale 

In [65]:
# if you want to identify one particular person then you give the features of that particular person only then it identify that particular person 
# but here we given the overall person features 

In [66]:
# load the features 
# ex: to detect the cars we design the car features 
# car features -> OpenCV liabrary -> car.xml         
# load the video 
# for every image  -> convert to black & white  (loop has to applied)
#               -> detect the features of car is available or not , if available identify if not available not identify 

# Car Detection 

In [89]:
import time 

# load the features 
car_classifier = cv2.CascadeClassifier('Haarcascades\haarcascade_car.xml')

# Initiate video capture for video file 
cap = cv2.VideoCapture('image_examples/cars.avi') 

# detect
while cap.isOpened(): # video opened 
    
    time.sleep(.01)
    check, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # convert first image (frame) to black & white  
    cars = car_classifier.detectMultiScale(gray, 1.4, 2) # after B & W detect MultiScale
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255),2)
        cv2.imshow('Cars', frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows() 

In [68]:
# how to improve the accuracy ? 
# 1. Scale Factor 2. n_neighbors ---> hyperparameter tuning 
# if you take the scale fator of 1.01 -> everytime it reduce the 1% zoomness -> time will be more 
# 1.1 -> 10% # 1.06 -> 6% # 1.5 -> 50% 
# if it is not identify in 1.5 then reduced to 1.4 , reducing to 1.3 , 1.2 , 1.1 
# 1.5 -> take less time
# 1.01 -> take more time 
# as it decreasing slowly, automatically the time will be more

In [76]:
# accuracy is the top priority  
# time is the second priority 

In [ ]:
# if we want to improve the accuracy 
# 1. we have to decrease the scale factor (1.01 is least)
# 2. try to increase the no. of neighbors , n_neighbors -> more identify 

# so either decrease the scale factor or increase the number of neighbors to increase your accuracy